### PR TITLE
Teach find_button() to find elements with attribute of role="button"

### PR DESCRIPTION
**Pull request by cworth-gh**
This is in addition to the other buttons it already knows how to find,
(such as `<input>` and `<button>`).

This commit includes a new test to verify the new functionality.

### CODE REVIEW

**Comment by koterpillar** [comment]
https://developer.mozilla.org/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role says not just `<a>` can be used as a button.

**Comment by cworth-gh** [comment]
Thanks for pointing that out.

I've now written the code to be more general, (matching any element with role="button"). I've also extended the testing to cover all of these supported button types:

```
<input type="submit">
<input type="reset">
<input type="button">
<input type="image">
<button>
<a role="button">
<div role="button">
<span role="button">
<p role="button">
```

Note that this latest pull request sits on top of the input-button pull-request, (since it is being tested as well), so you'll want to merge that other one first.

**Comment by koterpillar** [comment]
I've now merged the other pull request, and this one started failing tests.

**Comment by cworth-gh** [comment]
Thanks for merging the other. Sorry about the failure on this one---I had been running both pep8 and the test suite on my own, but I had neglected to run pylint, and I had accidentally copy/pasted a duplicate version of two of the test functions. That should all be resolved now.

**Comment by koterpillar** [comment]
Thanks, merged! Will release all the changes shortly.

**Comment by cworth-gh** [comment]
Thanks! I really appreciate your rapid responses and your attention to detail.

**Pull request merged**
